server:
  port: 8502
  context-path: /ui
  session:
    cookie:
      name: UISESSION
      

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: clientId
      client-secret: secret
      access-token-uri: http://localhost:8501/auth/oauth/token
      user-authorization-uri: http://localhost:8501/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:8501/auth/getCurrentUser
      
      
spring:
  thymeleaf:
    cache: false