spring:
  application:
    name: user-service
    
server:
  port: 8302
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
    
request:
  url : https://maps.googleapis.com/maps/api/geocode/json
  API_KEY: AIzaSyBRn_dBL2uppG8N0gUyLf9X7yK1uHdzELk